### PR TITLE
feat: Permalinks in Dataverse

### PR DESCRIPTION
**Pull request by vera**
**Status: draft**

_Open issues:_

- [x] how does this work for already created datasets with fake DOIs?

   I did not find an API to generate a new PID using a new provider for already existing datasets.

   I checked [here](https://guides.dataverse.org/en/latest/admin/dataverses-datasets.html) and [here](https://guides.dataverse.org/en/latest/api/native-api.html)

   Maybe we need to edit the existing datasets in the database?

- [x] how can we run the SQL script as part of the init job? I attempted to include the SQL script in the bootstrap job, but the configbaker image doesn't have `psql` installed and cannot connect to the DB to run it.

   When executing the SQL script manually, correct Permalinks are generated:

   image

   image

### CODE REVIEW

**Comment by johannes-darms** [comment]
We can open a ticket in dataverse and ask them to add psql into the config baker image. Most likely it will be added quite fast.

**Comment by johannes-darms** [comment]
> Note that any datasets or files created using a test configuration cannot be directly migrated to a production PID provider and would need to be created again once a valid PID Provider(s) are configured.
I found this information here: https://guides.dataverse.org/en/latest/installation/config.html#persistent-identifiers-and-publishing-datasets

**Comment by vera** [comment]
> We can open a ticket in dataverse and ask them to add psql into the config baker image. Most likely it will be added quite fast. Concerning the migration we need to ask Phil!

Done https://github.com/IQSS/dataverse/issues/10487

> > Note that any datasets or files created using a test configuration cannot be directly migrated to a production PID provider and would need to be created again once a valid PID Provider(s) are configured.
> 
> I found this information here: https://guides.dataverse.org/en/latest/installation/config.html#persistent-identifiers-and-publishing-datasets

Hm :/ I am wondering whether moving the dataset to a new collection maybe counts as "created again". Otherwise, I am also unsure if & how our idea with moving datasets to a DOI collection to create a DOI for them works. I can do a quick test of this.

**Comment by poikilotherm** [comment]
> I am wondering whether moving the dataset to a new collection maybe counts as "created again"
Short answer: nope. The association of a dataset to a collection is just metadata.

**Comment by johannes-darms** [comment]
Besides the one-time migration from FAKE DOIs to Permalinks. The process flow I envision is the following: 
1) A dataset is created within a dataverse (with configured PermaLink provider) and is not published.
2.A.1) The dataverse is moved into another dataverse with a configured DOI Provider, and still not published.
2.A.2) The datset is published, and as configured for the dataverse, a correct DOI will be minted.
2.B.1) The datset is published, and as configured for the dataverse, a correct PermaLink will be created.

**Comment by vera** [comment]
> Besides the one-time migration from FAKE DOIs to Permalinks. The process flow I envision is the following:
> 
> 1`) A dataset is created within a dataverse (with configured PermaLink provider) and is not published. 2.A.1) The dataverse is moved into another dataverse with a configured DOI Provider, and still not published. 2.A.2) The datset is published, and as configured for the dataverse, a correct DOI will be minted. 2.B.1) The datset is published, and as configured for the dataverse, a correct PermaLink will be created.

The difficulty I see with this is that Permalinks and DOIs are created/reserved by Dataverse when a dataset is created, not when it is published. As far as I understand, it is not currently intended by Dataverse to change the PID afterwards. But we could work on a PR for this.

**Comment by johannes-darms** [comment]
> > Besides the one-time migration from FAKE DOIs to Permalinks. The process flow I envision is the following:
> > 1`) A dataset is created within a dataverse (with configured PermaLink provider) and is not published. 2.A.1) The dataverse is moved into another dataverse with a configured DOI Provider, and still not published. 2.A.2) The datset is published, and as configured for the dataverse, a correct DOI will be minted. 2.B.1) The datset is published, and as configured for the dataverse, a correct PermaLink will be created.
> 
> The difficulty I see with this is that Permalinks and DOIs are created/reserved by Dataverse when a dataset is created, not when it is published. As far as I understand, it is not currently intended by Dataverse to change the PID after the inital creation. But we could work on a PR for this.

This means we need to adapt the move dataset functionality to also alter the reserved but no yet registers PID so it's consistent with the configured PID provider?

**Comment by vera** [comment]
> This means we need to adapt the move dataset functionality to also alter the reserved but no yet registers PID so it's consistent with the configured PID provider?

Yes I think so.

We could also implement, at least for the direction "Permalink/FAKE -> X" as a special case, that the PID of an already published dataset is replaced when moving. (see the Zulip discussion linked by Oliver)

If we implement the "FAKE -> X" case, it could also help us do the transition away from FAKE PIDs.

**Comment by johannes-darms** [comment]
First, as we only migrate once from FAKE to permalink, I'd rather do some easy SQL magic to improve our situation. I'm concerned about the needed resources.  

Second, when I can create a dataset in one dataverse, move it to another and publish it there. Assuming that both dataverse have different PID providers configured, the dataset will be minted with the wrong PID provider, right? That's unexpected behavior and should be resolved. The fix should be a rather small addition to the https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommand.java and will likely requires less resources than developing PID transition feature.

**Comment by vera** [comment]
> Second, when I can create a dataset in one dataverse, move it to another and publish it there. Assuming that both dataverse have different PID providers configured, the dataset will be minted with the wrong PID provider, right? That's unexpected behavior and should be resolved. The fix should be a rather small addition to the https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/MoveDatasetCommand.java and will likely requires less resources than developing PID transition feature.

I think we need a PID transition feature if we want to implement the use case of minting DOIs for already published datasets. If we only want to mint DOIs for unpublished datasets, yes it would be easier to implement (but incomplete).

**Comment by vera** [comment]
@johannes-darms I think this is ready to merge.

I found some more anomalies/studies that seem to be in the wrong collection: In the ICTRP collection, there are

- 18 entries with NCT ID. I assume these are all cases of studies where Germany was previously entered as a study location, but later removed (https://github.com/nfdi4health/csh-ui/issues/889). Example: NCT04777734 https://clinicaltrials.gov/search?cond=NCT04777734
- 11 entries with DRKS ID, apparently these were not included in the DRKS import for some reason, only included in the ICTRP import. Example: DRKS00029657 https://drks.de/search/de/trial/DRKS00029657

We might think about how to handle these

**Comment by johannes-darms** [comment]
> @johannes-darms I think this is ready to merge.

Great!

> I found some more anomalies/studies that seem to be in the wrong collection: In the ICTRP collection, there are
> 
>     * 18 entries with NCT ID. I assume these are all cases of studies where Germany was previously entered as a study location, but later removed ([Special cases of imported studies: how to handle them? csh-ui#889](https://github.com/nfdi4health/csh-ui/issues/889)). Example: NCT04777734 https://clinicaltrials.gov/search?cond=NCT04777734

For now, keep them.

>     * 11 entries with DRKS ID, apparently these were not included in the DRKS import for some reason, only included in the ICTRP import. Example: DRKS00029657 https://drks.de/search/de/trial/DRKS00029657
> 

That could be the case. Let's wait and see what changes once we update the WHO ICTRP data.

> We might think about how to handle these

We can discuss this in October during our meeting.

**Pull request merged**
